apiVersion: apps/v1
kind: Deployment
metadata:
  name: service0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service0
  template:
    metadata:
      labels:
        app: service0
    spec:
      containers:
        - name: service0
          command:
            - /httpserver
            - --debug=1
          imagePullPolicy: IfNotPresent
          image: 463045792/apiserver:v4.0
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: service0
spec:
  ports:
    - name: http-service0
      port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app: service0
  type: NodePort