apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          command:
            - /httpserver
            - --debug=1
          imagePullPolicy: IfNotPresent
          image: 463045792/apiserver:v4.1
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
    - name: http-service1
      port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app: service1
  type: NodePort