apiVersion: v1
data:
  PORT: 8082
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-27T15:44:54Z"
  name: httpserver-config
  namespace: default
  resourceVersion: "1819243"
  uid: 3b0c72bf-ae62-4ef6-8581-78bddefa998c