apiVersion: v1
kind: Service
metadata:
  annotations:
    app: httpserver
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    lan: golang
    maintainer: jiac
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "80"
      port: 80  # virtualIp port
      targetPort: 8082  # real server port, what's more, real Ips are Ips of pods filtered by "selector"
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    io.kompose.service: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
