apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: # Dockerfile LABEL
    app: httpserver
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    lan: golang
    maintainer: jiac
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: #
    type: Recreate
  selector: #
    matchLabels:
      app: httpserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
        app: httpserver
    spec:
      containers:
        - args:
            #启动参数
            - /bin/httpserver
            - -debug=1
        - env:
            #环境变量
            - name: PORT
              value: "8082"
            - name: version
              value: "1.0"
            #身份认证
            - name: name
              valueFrom:
                secretKeyRef:
                  name: httpserver-secret
                  key: name
            - name: pwd
              valueFrom:
                secretKeyRef:
                  name: httpserver-secret
                  key: pwd
          image: 463045792/httpserver:vlog
          name: httpserver
          ports:
            - containerPort: 8082
          resources: { }
      restartPolicy: Always
status: { }
