apiVersion: v1
kind: Service
metadata:
  annotations:
    maintainer: jiac
#  labels:
#    app: httpserver
  name: web
spec:
  ports:
    - name: "80"
      port: 80  # virtualIp port
      targetPort: 8082  # real server port, what's more, real Ips are Ips of pods filtered by "selector"
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    app: httpserver
  sessionAffinity: None
  type: NodePort

