apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: httpserver
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
    lan: golang
    maintainer: jiac
  creationTimestamp: "2021-11-28T09:50:37Z"
  generation: 1
  labels:
    io.kompose.service: web
  name: web
  namespace: default
  resourceVersion: "1890713"
  uid: e8f2247e-3541-4089-b2c5-53ceefd84a5b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpserver
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpserver
        io.kompose.service: web
    spec:
      containers:
        - args:
            - /bin/httpserver
            - -debug=1
          env:
            - name: PORT
              value: "8082"
            - name: version
              value: "1.0"
            - name: name
              valueFrom:
                secretKeyRef:
                  key: name
                  name: httpserver-secret
            - name: pwd
              valueFrom:
                secretKeyRef:
                  key: pwd
                  name: httpserver-secret
          image: 463045792/httpserver:vlog
          imagePullPolicy: IfNotPresent
          name: httpserver
          ports:
            - containerPort: 8082
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2021-11-28T09:50:39Z"
      lastUpdateTime: "2021-11-28T09:50:39Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-11-28T09:50:37Z"
      lastUpdateTime: "2021-11-28T09:50:39Z"
      message: ReplicaSet "web-cb9674df8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1